#+title: Timebomb of approximation method in physics

* Introduction

Approximation method is yet essentensial topic in physics. Physicists love approximations, like in functional expansion for getting polynomials for their ease or may be specialized idealization in perticular topic. There is too much advantages of approximation methods like *doing physics* instead going maze of exactness in mathematics. Getting interpretation or more i say knowing system is sometime important then going for regorious mathematics. For example, famous equation of fluid dynamics *Navier-Stoke equation* can be imposible to solve but as physicist they know what it is.

Be aware, that approximation is just approximation. We should remember everytime we do that. Sometime we forgot actual system which is far from ideal. We should know that we are on mission to know nature not just building new theories.

Let's dive into one example, what do i imply by consequences of approximation methods. In classical mechanics, we have 3 or 4 major thoeries, like Centre forces oscillations. In Oscillation theory we studied *Simple Harmonic Osciallations*, but as we are going to see that simple harmonic oscillation is not exactly that simple.

* Harmonic Oscillator

Classical example of oscillator as we studied in physics is pendulum. By understanding pendulum means understanding most of physics of oscillators, in sense atoms, dipoles or any periodic motion. Let's build our Pendulum. We take small bob (as we can structure) with mass $m$, which is attached to string of $l$ with rigid wall. Mass $m$ suspended vertically with gravity. We should take nonconservative force like damping to make our system feel more practical.  
